---
#Set up a kubernetes cluster
- hosts: k_cluster

  tasks:
          - name: Stop firewalld
            service: 
                name: firewalld
                enabled: no
                state: stopped
            #This needs a reboot afterwards
          - name: Disable SELinux
            selinux:
                policy: targeted
                state: permissive
          - name: Change hostname
            hostname:
                name: "{{ hostname }}"
          - name: Install docker
            yum: 
                name: docker
                state: present
          - name: Enable and start docker
            service:
                name: docker
                enabled: yes
                state: started
          - name: Install Google Cloud SDK yum repository
            copy:
                src: templates/google-cloud.repo
                dest: /etc/yum.repos.d/
          - name: Install Kubernetes yum repository
            copy:
                src: templates/kubernetes.repo
                dest: /etc/yum.repos.d/
          - name: Install kubernetes packages
            yum:
                name: kubectl, kubelet, kubeadm
                state: present
          - name: Enable and start kubelet
            service: 
                name: kubelet
                enabled: yes
                state: started
                
# Set up the master node
- hosts: k_master

  tasks:
        - name: Create user kubeta
          user:
                name: kubeta
                comment: "Kubeta"
                state: present
        - name: Install ssh key to kubeta
          authorized_key:
                user: kubeta
                state: present
                key: "{{ lookup('file', '/home/tale/Ansible/ans_ssh.pub') }}"
        - name: Create dir ~/.kube for user kubeta
          file:
                path: /home/kubeta/.kube
                state: directory
                owner: kubeta
                group: kubeta
                mode: 0750
                
                
